### ISSUE TITLE
user-end API

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/mesmerize-viz#21]
instead of making complex widgets with dropdown etc. we can just have the user specify what they want in each part of the gridplot.

### Simple example 

```python
from mesmerize_viz.widgets import CNMFWidget
from mesmerize_viz.visuals import cnmf_visuals as cvs

shape = (2, 2)
visualizations = [
    [cvs.input + cvs.contours,  # input movie + contours
     cvs.rcm + cvs.contours,  # these get stacked in the z-axis in the order of addition 
     cvs.lineplot],

    [cvs.rcb,
     cvs.residuals,
     cvs.heatmap(cmap="viridis")]  # maybe allow these to be optionally callable with kwargs
]

names = [
    ["input", "rcm", "traces"],
    ["rcb", "residuals", "heatmap"]
]

sliders =\  # slider(s) linked according to this
    [[0,     0,     None],
     [0,     0,     None]]

# events to link visuals together, the details are predefined by us using the fastplotlib API
events = [
    cvs.contours >> cvs.heatmap,
    cvs.heatmap >> cvs.contours,
    cvs.heatmap >> cvs.lineplot
]

Make the visualization
cnmf_viz = CNMFWidget(
    shape=(2, 3),  # makes gridplot of [2, 3]
    visualizations=visualizations,
    sliders=sliders,
    events=events,
    selection="single"  # single select batch items
)

cnmf_viz.show()
```

### Multi selection

```python3
# set properties of visuals like this
cnmf_viz["input"].cmap = "gnuplot2"

cnmf_viz["input"].contours = "good-bad"
cnmf_viz["rcm"].contours = "index"

# multi-selection works exactly the same, stuff is added to grid in the order that they user selects them

visualizations_multi = [
    [cvs.input + cvs.contours,
     cvs.input + cvs.contours,
     cvs.input + cvs.contours,]

    [cvs.input + cvs.contours,
     cvs.input + cvs.contours,
     cvs.input + cvs.contours,]
]

cnmf_viz_multi = CNMFWidget(
    shape=(2, 3),  # makes gridplot of [2, 3]
    visualizations=visualizations_multi,
    sliders="sync-all", # all subplots get a single slider that synced them all
    events=None,
    selection="multi"  # multi select batch items
)
```

### Customizability 

```python3
# customize visuals even more
# a function that just returns dfof traces
def custom_temporal(cnmf_item: pd.Series) -> np.ndarray:
    cnmf_item.run_detrend_dfof()
    return cnmf_item.get_detrend_dfof()

# make reconstructed movie with dfof traces instead of raw `cnmf_obj.C` temporal components
rcm_custom= cvs.rcm(temporal=custom_temporal)

visualizations = [
    [cvs.input + cvs.contours,
     rcm_custom,  # RCM with the dfof used for temporal
     cvs.lineplot],

    [cvs.rcb,
     cvs.residuals,
     cvs.heatmap(cmap="viridis")]  # maybe allow these to be optionally callable with kwargs
]

cnmf_viz = CNMFWidget(
    shape=(2, 3),  # makes gridplot of [2, 3]
    visualizations=visualizations_multi,
    sliders="sync-all", # all subplots get a single slider that synced them all
    events=None,
    selection="multi"  # multi select batch items
)
```

@clewis7 this will be so much easier to implement 
@EricThomson comments?

**Comment by EricThomson** [comment]
Caveat:  take my thoughts with a grain of salt, as the code is hard for me to understand without digging in more. Just some impressions here!

It seems you are creating a unique logic or syntax of visual representations that allows people freedom to compose/embed/concatenate/stack views using fastplotlib visualizations in mesmerize-viz. This seems very cool!

It is a little similar to the holoviews syntax in places, which worries me a bit. The danger with this is that you are writing it so it will seem super intuitive and simple to you, but not to people onboarding. E.g., with holoviews the slogan is 'annotate your data and let it visualize itself.'  But it often doesn't feel like that: it sometimes feels like R syntax trying to trick me into thinking it is Pythonic (e.g., with concatenation operators and `>>` operators things can sometimes be onfusing). One of the nice things about fastplotlib is it feels like matplotlib in a lot of the right places, but with magic notebook superpowers.

Because of that, I'd watch out for too many neologisms (some are fine I'm sure but I'd be really cautious). I may well be wrong here, and am almost certainly missing wrinkles and nuances: I'm just saying the more it reads like standard Python/plotting libraries the more enthusiastic adoption you will get, is my guess. 

I'd obviously have to do a much deeper dive into what is actually happening at the different levels here to really speak much to all the specifics. I'm sure the functionality is good, but I wonder if there is a way to reproduce it with a bit less novel syntactic sugar?

For instance, would it be awful if instead of novel operators, you just exposed novel functions? I think newcomers in general are really comfortable with functions, and generating objects defined using the functions. 

I assume the worry is that the composition of function upon function would start to get really messy and hard to read? If so I could see that just using new operators would make things way more readable. 

Something I'd need to think about tbh. 

I guess one option is make it matplotlib-esque and have a functional and a more streamlined api. Teach the functional first for newcomers, and then the more streamlined operator-based one. Sort of like matplotlib has the pyplot interface to start with, but then power users all use the object oriented api. 

Obviously I'm just brainstorming here: the option I just mentioned sounds like a lot of work to implement!

**Comment by kushalkolar** [comment]
@EricThomson 

> It seems you are creating a unique logic or syntax of visual representations that allows people freedom to compose/embed/concatenate/stack views using fastplotlib visualizations in mesmerize-viz

This API would be specific to `mesmerize-viz`, allowing them to put CNMF/Mcorr outputs where they want and combine/compose them easily.

> It is a little similar to the holoviews syntax in places, which worries me a bit. The danger with this is that you are writing it so it will seem super intuitive and simple to you

yes kinda, like how I show for "z-stacking" visualizations:

```python3
    [cvs.input + cvs.contours,  # input movie + contours
     cvs.rcm + cvs.contours,  # these get stacked in the z-axis in the order of addition 
     cvs.lineplot],
```

This could instead be done as a list of tuples or something without the syntactic sugar. We could give both options.

```python3
   [(cvs.input, cvs.contours),  # input movie + contours
     (cvs.rcm, cvs.contours),  # these get stacked in the z-axis in the order of addition 
     cvs.lineplot],


> sometimes feels like R syntax trying to trick me into thinking it is Pythonic (e.g., with concatenation operators and >> operators

Could instead use a function like this for the events

```python3
events = [
    cvs.contours.connect(cvs.heatmap),
    cvs.heatmap.connect(cvs.contours),
    cvs.heatmap.connect(cvs.lineplot)
]
